### ISSUE TITLE
Local Research Group LLM-Foundry Quick Start in Modal using SmolLM2-135M with Flash Attention 2

### ISSUE THREAD

**Issue by vishalbakshi** [LocalResearchGroup/llm-foundry#14]
I have trained (using the Quick Start script) smollm2-135M both with `model.use_flash_attention_2=false` and `model.use_flash_attention_2=true`. When set to `true` the final batch train time is `0.0011`, when set to `false` it's `0.0014` (my guess is the units are _hours_). I don't know if that difference is significant enough to say that `model.use_flash_attention_2=true` is using Flash Attention 2 but the output of:

```python
import flash_attn
print(f"Flash Attention version: {flash_attn.__version__}")
```
is:

```
Flash Attention version: 2.7.3
```

Which is the latest version on PyPI (January 11, 2025).

## Training with flash attention

I am installing flash attention as is recommended by the HuggingFace Alignment Handbook (which is linked in the SmolLM2-135M model card) with

```
RUN python -m pip install flash-attn --no-build-isolation
```

And then calling `pip install -e .` instead of `pip install -e ".[gpu]"` so that we don't run the extra dependency of `flash_attn==2.6.3` in `setup.py`.

Here's the full Dockerfile I'm using. Note that to force a rebuild of the image in Modal add `MODAL_FORCE_BUILD=1` before `modal run` like so: `MODAL_FORCE_BUILD=1 modal run quick-start.py`:

```Dockerfile
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    build-essential \
    ninja-build \
    && rm -rf /var/lib/apt/lists/*

# Create symlinks
RUN ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf /usr/bin/pip3 /usr/bin/pip

# Set CUDA_HOME
ENV CUDA_HOME=/usr/local/cuda

# Install base Python dependencies
RUN python -m pip install cmake packaging torch numpy

# Install flash-attention as specified in SmolLM2 recipe
RUN python -m pip install flash-attn --no-build-isolation

# Clone and install llm-foundry from specific branch
RUN git clone -b smollm2-135m-training https://github.com/LocalResearchGroup/llm-foundry.git && \
    cd llm-foundry && \
    python -m pip install -e .
```

I have created a `smollm2-135m-training` branch with the following _smollm2-135m.yaml_:

```YAML
variables:
  data_local: ./my-copy-c4
  data_remote:  # If blank, files must be present in data_local
  tokenizer_name: HuggingFaceTB/SmolLM2-135M
  global_seed: 17
  max_seq_len: 2048
  run_name:  # If left blank, will be read from env var $RUN_NAME

max_seq_len: ${variables.max_seq_len}
run_name: ${variables.run_name}

# Model
model:
  name: hf_causal_lm
  pretrained_model_name_or_path: HuggingFaceTB/SmolLM2-135M
  config_overrides:
    max_position_embeddings: ${variables.max_seq_len}
  use_flash_attention_2: true  # Moved outside of config_overrides
  pretrained: false

# Tokenizer
tokenizer:
  name: ${variables.tokenizer_name}
  kwargs:
    model_max_length: ${variables.max_seq_len}

# Rest of the configuration remains similar to your example, but let's adjust some parameters
train_loader:
  name: text
  dataset:
    local: ${variables.data_local}
    remote: ${variables.data_remote}
    split: train
    shuffle: true
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${variables.data_local}
    remote: ${variables.data_remote}
    split: val
    shuffle: false
    max_seq_len: ${variables.max_seq_len}
    shuffle_seed: ${variables.global_seed}
  drop_last: false
  num_workers: 8

scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 4800ba
eval_interval: 500ba
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 256

# System
seed: ${variables.global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 16
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
```

I'm using the following script to run on Modal with an A100 GPU. Note I had to lower the batch size to `2` to avoid getting a CUDA OOM error:

```python
from modal import Image, App, gpu

app = App("lrg-llm-foundry-smollm2-135m-training")

# Build image from local Dockerfile
image = Image.from_dockerfile("Dockerfile")

@app.function(gpu="a100", image=image, timeout=3600)
def run_quickstart():
    import subprocess
    import os

    # Change to llm-foundry/scripts directory at the start
    os.chdir("/llm-foundry/scripts")
    print(f"Working directory: {os.getcwd()}")
    
    # Step 1: Convert C4 dataset
    print("Converting C4 dataset...")
    data_prep_cmd = [
        "python", "data_prep/convert_dataset_hf.py",
        "--dataset", "allenai/c4",
        "--data_subset", "en",
        "--out_root", "/root/my-copy-c4",
        "--splits", "train_small", "val_small",
        "--concat_tokens", "2048",
        "--tokenizer", "HuggingFaceTB/SmolLM2-135M",
        "--eos_text", "<|endoftext|>"
    ]
    result = subprocess.run(data_prep_cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print("Data prep errors:", result.stderr)
    
    # Step 2: Train the model
    print("\nTraining model...")
    train_cmd = [
        "composer",
        "train/train.py",
        "train/yamls/pretrain/smollm2-135m.yaml",
        "variables.data_local=/root/my-copy-c4",
        "train_loader.dataset.split=train_small",
        "eval_loader.dataset.split=val_small",
        "max_duration=10ba",
        "eval_interval=0",
        "save_folder=/root/smollm2-135m",
        "device_train_microbatch_size=2",
        "global_train_batch_size=2",
        "device_train_batch_size=2"  
    ]
    result = subprocess.run(train_cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print("Training errors:", result.stderr)
    if result.returncode != 0:
        raise Exception(f"Training failed with exit code {result.returncode}\nStderr: {result.stderr}")
    
    # Step 3: Convert model to HuggingFace format
    print("\nConverting model to HuggingFace format...")
    convert_cmd = [
        "python", "inference/convert_composer_to_hf.py",
        "--composer_path", "/root/smollm2-135m/ep0-ba10-rank0.pt",  # Changed input path
        "--hf_output_path", "/root/smollm2-135m-hf",  # Changed output path
        "--output_precision", "bf16"
    ]
    result = subprocess.run(convert_cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print("Conversion errors:", result.stderr)
    
    # Step 4: Evaluate the model
    print("\nEvaluating model...")
    eval_cmd = [
        "composer",
        "eval/eval.py",
        "eval/yamls/hf_eval.yaml",
        "icl_tasks=eval/yamls/copa.yaml",
        "variables.model_name_or_path=/root/smollm2-135m-hf"  # Changed model path
    ]
    result = subprocess.run(eval_cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print("Evaluation errors:", result.stderr)
    
    # Step 5: Generate test responses
    print("\nGenerating test responses...")
    generate_cmd = [
        "python", "inference/hf_generate.py",
        "--name_or_path", "/root/smollm2-135m-hf",  # Changed model path
        "--max_new_tokens", "256",
        "--prompts",
        "The answer to life, the universe, and happiness is",
        "Here's a quick recipe for baking chocolate chip cookies: Start by"
    ]
    result = subprocess.run(generate_cmd, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print("Generation errors:", result.stderr)
    
    return "Quickstart completed!"


@app.local_entrypoint()
def main():
    print(run_quickstart.remote())
```

Here are the `Train time/train` output values for each batch. Note that I'm unclear exactly what this value means but given that it increases linearly I'm guessing it's the accumulated training time (in hours)?

|Batch|`Train time/train`|
|:-:|:-:|
|1|0.0007
|2|0.0008
|3|0.0008
|4|0.0009
|5|0.0009
|6|0.0010
|7|0.0010
|8|0.0011
|9|0.0011
|10|0.0011

Note that below you'll see that without flash attention the final batch time was 0.0014 so I think this shows that it is using flash attention when `use_flash_attention_2=true`.

## Training without flash attention

I modified the Modal script's `train_cmd`, adding `"model.use_flash_attention_2=false"` and got the following results (it takes a bit longer to finish training):

|Batch|`Train time/train`|
|:-:|:-:|
|1|0.0007
|2|0.0007
|3|0.0008
|4|0.0009
|5|0.0010
|6|0.0011
|7|0.0011
|8|0.0012
|9|0.0013
|10|0.0014
